### ISSUE TITLE
current_user() -> User

### ISSUE THREAD

**Issue by madgagarin** [pahrohfit/sanic-praetorian#43]
Hello. In this form, it would be convenient to use:
current_user() -> User

 If it was meant to be, what's the point?
current_user() -> object

**Comment by pahrohfit** [comment]
Yeah, you are correct, was just lazy docstring by me. Updated in dev -- 7ac677e22d16df53440ac5c7ed022bf1cf1caab4

**Comment by pahrohfit** [comment]
#
