### ISSUE TITLE
Incompatible with CPy3.12

### ISSUE THREAD

**Issue by BGarber42** [pahrohfit/sanic-praetorian#54]
Depends on `pendulum<3.0,>=2.1` but `pendulum<3.0.0b1` has a dependency on `distutils` which was removed in python 3.12

**Comment by pahrohfit** [comment]
Will take a look

**Comment by pahrohfit** [comment]
Check out 2.3.1

**Comment by pahrohfit** [comment]
No response, but unit tests passing after updates
